import argparse
import json
from pathlib import Path
import time

from .actions import BUTTONS, Segment
from .bridge import Bridge, BridgeError


def initialize(root: Path, reset=False):
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    if (root / "start.lua").exists() and not reset:
        raise BridgeError("Bridge already initialized. To reset, stop its Lua script, then use init --reset.")
    if reset:
        for name in ("ready.json", "response.json", "request.txt", "request.tmp", "pending.json", "client.lock"):
            (root / name).unlink(missing_ok=True)
    (root / "images").mkdir(exist_ok=True)
    (root / "responses").mkdir(exist_ok=True)
    source = Path(__file__).with_name("bridge.lua").resolve()
    # Forward-slash absolute paths work in Windows Lua, including spaces.
    quote = lambda p: json.dumps(p.as_posix(), ensure_ascii=False)
    script = f"-- Generated by gpt64. Stop this script before resetting.\nassert(loadfile({quote(source)}))({{root = {quote(root)}}})\n"
    (root / "start.lua").write_text(script, encoding="utf-8")
    return root / "start.lua"


def show(observation):
    print(json.dumps({"image": str(observation.image), "frame_before": observation.frame_before,
                      "frame_after": observation.frame_after, "advanced": observation.advanced}, indent=2))


def main(argv=None):
    parser = argparse.ArgumentParser(description="Paused, vision-only Mario 64 emulator harness")
    parser.add_argument("--bridge", type=Path, default=Path(".gpt64/bridge"))
    parser.add_argument("--timeout", type=float, default=20)
    commands = parser.add_subparsers(dest="command", required=True)
    init = commands.add_parser("init", help="Generate a Lua launcher")
    init.add_argument("--reset", action="store_true", help="Reset mailboxes after stopping Lua; retain logs/images")
    commands.add_parser("doctor", help="Check live N64 bridge and screenshot")
    commands.add_parser("observe", help="Screenshot without advancing time")
    smoke = commands.add_parser("smoke", help="Check exact frame stepping and frozen idle")
    smoke.add_argument("--idle-seconds", type=float, default=2)
    step = commands.add_parser("step", help="Hold controls for a bounded number of frames")
    step.add_argument("--frames", type=int, default=12)
    step.add_argument("--x", type=float, default=0)
    step.add_argument("--y", type=float, default=0)
    step.add_argument("--button", action="append", choices=BUTTONS, default=[])
    sequence = commands.add_parser("sequence", help="Execute a JSON array of controller segments")
    sequence.add_argument("file", type=Path)
    dashboard = commands.add_parser("serve", help="Open the local observer dashboard and vision agent")
    dashboard.add_argument("--port", type=int, default=8765)
    dashboard.add_argument("--runs", type=Path, default=Path(".gpt64/runs"))
    dashboard.add_argument("--demo", action="store_true", help="Synthetic UI demo, no emulator or API requests")
    dashboard.add_argument("--reasoning", choices=("low", "medium", "high", "xhigh", "max"), default="medium")
    dashboard.add_argument("--billing", choices=("chatgpt", "api"), default="chatgpt", help="ChatGPT plan by default; paid API is an explicit choice")
    check = commands.add_parser("api-check", help="Read-only check of exact gpt-6.1-sol access")
    check.add_argument("--billing", choices=("chatgpt", "api"), default="chatgpt")
    login = commands.add_parser("login", help="Continue with ChatGPT in your system browser")
    login.add_argument("--new", action="store_true", help="Register another account/workspace")
    login.add_argument("--enable-plan", action="store_true", help="Explicitly ask again for ChatGPT plan permission")
    commands.add_parser("logout", help="Revoke the selected ChatGPT renewable session and clear its tokens")
    commands.add_parser("accounts", help="Show saved ChatGPT account labels and IDs, never tokens")
    account = commands.add_parser("account", help="Select a saved ChatGPT account")
    account.add_argument("client_id")
    commands.add_parser("instructions", help="Print the instructions the Mario agent receives each turn")
    args = parser.parse_args(argv)
    try:
        if args.command == "instructions":
            from .model import INSTRUCTIONS
            print(INSTRUCTIONS)
            return 0
        if args.command in ("login", "logout", "accounts", "account"):
            from .auth import AuthStore
            store = AuthStore()
            if args.command == "login":
                print("Opening Continue with ChatGPT. Grant plan usage in the OpenAI browser page. Waiting up to 10 minutes.")
                info = store.login(args.new, args.enable_plan)
                print(f"Account: {info['label']}. ChatGPT plan use {'enabled' if info['ready'] else 'not granted'}. No inference was sent.")
                if info["ready"]:
                    print("You're using your ChatGPT plan. Manage usage and app credit limits in ChatGPT Settings > Usage.")
                    store.acknowledge()
            elif args.command == "logout":
                print("Signed out." if store.logout() else "Signed out locally; remote revocation unconfirmed. Disconnect gpt64 in ChatGPT Settings.")
            elif args.command == "account":
                store.select(args.client_id)
                print(store.public()["label"])
            else:
                print(json.dumps(store.public(), indent=2))
            return 0
        if args.command == "api-check":
            from .model import OpenAIClient, PlanClient
            client = PlanClient() if args.billing == "chatgpt" else OpenAIClient()
            print(f"{args.billing} model access verified: {client.check()}. No generation request was sent.")
            return 0
        if args.command == "serve":
            from .server import serve
            if not 0 <= args.port <= 65535:
                raise ValueError("Port must be between 0 and 65535")
            serve(args.bridge, args.runs, args.port, args.demo, args.reasoning, args.billing)
            return 0
        if args.command == "init":
            print(f"Open this script in BizHawk's Lua Console:\n{initialize(args.bridge, args.reset)}")
            return 0
        if args.command == "smoke" and not 0 <= args.idle_seconds <= 30:
            raise ValueError("idle-seconds must be between 0 and 30")
        segments = None
        if args.command == "step":
            segments = (Segment(args.frames, args.x, args.y, tuple(args.button)),)
        elif args.command == "sequence":
            data = json.loads(args.file.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                raise ValueError("sequence must be a JSON array")
            segments = tuple(Segment(**item) for item in data)
        with Bridge(args.bridge, args.timeout) as bridge:
            if segments is not None:
                show(bridge.step(segments))
            elif args.command == "smoke":
                first = bridge.observe()
                time.sleep(args.idle_seconds)
                second = bridge.observe()
                if first.frame_after != second.frame_before:
                    raise BridgeError("Emulator advanced while idle")
                stepped = bridge.step((Segment(30),))
                if stepped.frame_before != second.frame_after:
                    raise BridgeError("Emulator advanced between requests")
                time.sleep(args.idle_seconds)
                final = bridge.observe()
                if final.frame_before != stepped.frame_after:
                    raise BridgeError("Emulator advanced after action")
                print("PASS: observe advanced 0 frames; action advanced 30 frames; idle stayed frozen.")
                show(final)
            else:
                show(bridge.observe())
                if args.command == "doctor":
                    print(f"N64 bridge ready; buttons: {', '.join(bridge.ready['buttons'])}")
        return 0
    except (RuntimeError, ValueError, TypeError, OSError) as e:
        print(f"gpt64: {e}")
        return 1
