import argparse
import json
from pathlib import Path
import time

from .actions import BUTTONS, Segment
from .bridge import Bridge, BridgeError


def initialize(root: Path, reset=False):
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    if (root / "start.lua").exists() and not reset:
        raise BridgeError("Bridge already initialized. To reset, stop its Lua script, then use init --reset.")
    if reset:
        for name in ("ready.json", "response.json", "request.txt", "request.tmp", "pending.json", "client.lock"):
            (root / name).unlink(missing_ok=True)
    (root / "images").mkdir(exist_ok=True)
    (root / "responses").mkdir(exist_ok=True)
    source = Path(__file__).with_name("bridge.lua").resolve()
    # Forward-slash absolute paths work in Windows Lua, including spaces.
    quote = lambda p: json.dumps(p.as_posix(), ensure_ascii=False)
    script = f"-- Generated by gpt64. Stop this script before resetting.\nassert(loadfile({quote(source)}))({{root = {quote(root)}}})\n"
    (root / "start.lua").write_text(script, encoding="utf-8")
    return root / "start.lua"


def show(observation):
    print(json.dumps({"image": str(observation.image), "frame_before": observation.frame_before,
                      "frame_after": observation.frame_after, "advanced": observation.advanced}, indent=2))


def main(argv=None):
    parser = argparse.ArgumentParser(description="Paused, vision-only Mario 64 emulator harness")
    parser.add_argument("--bridge", type=Path, default=Path(".gpt64/bridge"))
    parser.add_argument("--timeout", type=float, default=20)
    commands = parser.add_subparsers(dest="command", required=True)
    init = commands.add_parser("init", help="Generate a Lua launcher")
    init.add_argument("--reset", action="store_true", help="Reset mailboxes after stopping Lua; retain logs/images")
    commands.add_parser("doctor", help="Check live N64 bridge and screenshot")
    commands.add_parser("observe", help="Screenshot without advancing time")
    smoke = commands.add_parser("smoke", help="Check exact frame stepping and frozen idle")
    smoke.add_argument("--idle-seconds", type=float, default=2)
    step = commands.add_parser("step", help="Hold controls for a bounded number of frames")
    step.add_argument("--frames", type=int, default=12)
    step.add_argument("--x", type=float, default=0)
    step.add_argument("--y", type=float, default=0)
    step.add_argument("--button", action="append", choices=BUTTONS, default=[])
    sequence = commands.add_parser("sequence", help="Execute a JSON array of controller segments")
    sequence.add_argument("file", type=Path)
    args = parser.parse_args(argv)
    try:
        if args.command == "init":
            print(f"Open this script in BizHawk's Lua Console:\n{initialize(args.bridge, args.reset)}")
            return 0
        if args.command == "smoke" and not 0 <= args.idle_seconds <= 30:
            raise ValueError("idle-seconds must be between 0 and 30")
        segments = None
        if args.command == "step":
            segments = (Segment(args.frames, args.x, args.y, tuple(args.button)),)
        elif args.command == "sequence":
            data = json.loads(args.file.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                raise ValueError("sequence must be a JSON array")
            segments = tuple(Segment(**item) for item in data)
        with Bridge(args.bridge, args.timeout) as bridge:
            if segments is not None:
                show(bridge.step(segments))
            elif args.command == "smoke":
                first = bridge.observe()
                time.sleep(args.idle_seconds)
                second = bridge.observe()
                if first.frame_after != second.frame_before:
                    raise BridgeError("Emulator advanced while idle")
                stepped = bridge.step((Segment(30),))
                if stepped.frame_before != second.frame_after:
                    raise BridgeError("Emulator advanced between requests")
                time.sleep(args.idle_seconds)
                final = bridge.observe()
                if final.frame_before != stepped.frame_after:
                    raise BridgeError("Emulator advanced after action")
                print("PASS: observe advanced 0 frames; action advanced 30 frames; idle stayed frozen.")
                show(final)
            else:
                show(bridge.observe())
                if args.command == "doctor":
                    print(f"N64 bridge ready; buttons: {', '.join(bridge.ready['buttons'])}")
        return 0
    except (BridgeError, ValueError, TypeError, OSError) as e:
        print(f"gpt64: {e}")
        return 1
